on:
  issues:
    types: [opened]

  pull_request:
    types: [opened, closed]

  pull_request_review_comment:
    types: [created]

  issue_comment:
    types: [created]

jobs:
  notify_discord:
    runs-on: ubuntu-latest
    steps:
      - name: Actions Status Discord
        uses: sarisia/actions-status-discord@v1.13.0
        if: always()
        with:
          status: ${{ job.status }}
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          title: >
            ${{ github.event_name }}: 
            ${{ github.event.issue.title || github.event.pull_request.title || 'Event Occurred' }}
            URL: 
            ${{ github.event.issue.html_url || github.event.pull_request.html_url || github.event.comment.html_url || 'No URL available' }}
